name: Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 2 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run:
          # python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run:
          python -m pytest --cache-clear -s -v --html=Reports/report.html testCases/Test.py
          # pytest

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: python -m pytest-report
          path: reports/report.html
